extends: base.yaml

env:
  id: LunarLanderContinuous-v2
  normalize_obs: true
  normalize_reward: true

method: actor_critic
algorithm: ppo
gamma: 0.99
gae_lambda: 0.95
clip_ratio: 0.2
entropy_coef: 0.0
value_coef: 0.5
max_grad_norm: 0.5

ppo_rollout:
  steps_per_update: 4096
  num_minibatches: 64
  update_epochs: 10

optimizer:
  lr: 0.0003

train_steps: 1000000
