extends: base.yaml

env:
  id: CartPole-v1

method: value_based
algorithm: q_learning_replay           # general name; implemented as DQN
gamma: 0.99

replay:
  capacity: 100000
  batch_size: 64
  start_learning: 1000

exploration:
  schedule: linear
  eps_start: 1.0
  eps_end: 0.05
  eps_decay_steps: 50000

target_network:
  type: hard
  update_every: 1000

optimizer:
  lr: 0.001

train_steps: 200000
